import {createSlice, PayloadAction} from '@reduxjs/toolkit';

// Types
import {UserSliceParams} from '../types';

// Initial state for the user slice
const initialState: UserSliceParams = {
  isLogin: false,
};

// Create the user slice, which contains reducers to modify the user state
export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    // Reducer to handle login action, which updates the isLogin state
    setLogin: (
      state: UserSliceParams,
      action: PayloadAction<UserSliceParams>,
    ) => {
      state.isLogin = action.payload.isLogin;
    },
  },
});

// Export the action creators generated by createSlice
export const {setLogin} = userSlice.actions;

// Export the reducer to be added to the store
export default userSlice.reducer;
